"""create world id proof uses

Revision ID: 76eb8b0fc03c
Revises:
Create Date: 2026-09-26 11:06:59.399233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76eb8b0fc03c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_id_proof_uses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rp_id', sa.String(length=128), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('nullifier', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rp_id', 'environment', 'action', 'identifier', 'nullifier', name='uq_world_id_proof_use_replay')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_id_proof_uses')
    # ### end Alembic commands ###
